<?php
/**
 * Created by PhpStorm.
 * User: slava
 * Date: 6/7/18
 * Time: 9:46 PM
 */

namespace AssessmentApp\Entities;


class NodeMetadataCollection extends \ArrayObject implements \JsonSerializable
{
    public function offsetSet($index, $newval)
    {
        if (!$this->isValidValue($newval)){
            throw new \InvalidArgumentException('value must be of type ' . NodeMetadata::class);
        }
        parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    }

    public function append($value)
    {
        if (!$this->isValidValue($value)){
            throw new \InvalidArgumentException('value must be of type ' . NodeMetadata::class);
        }

        parent::append($value); // TODO: Change the autogenerated stub
    }

    private function isValidValue($value)
    {
        return $value instanceof NodeMetadata;
    }

    /**
     * @inheritdoc
     */
    public function jsonSerialize()
    {
        return get_object_vars($this);
    }
}